services:
  frontend_react_with_rest:
    build:
      args:
      - BACKEND_API_URL=${BACKEND_API_URL}
      context: ./frontend_react_with_rest
    environment:
      PORT: 80
    ports:
    - 80:80
  rest_dotnet:
    build:
      context: ./rest_dotnet
    environment:
      PORT: 5000
    ports:
    - 5000:5000
version: '3.9'
